#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/mnt \
	/rrshare

HOST_MACHINE=$(uname -m)
DEFAULT_PACKAGE_PATH=/defaults/$HOST_MACHINE
UPGRADE_PACKAGE_PATH=/upgrades/$HOST_MACHINE

# install default
if [ ! -f /rrshare/rrshareweb ]; then
  echo "Installing ${HOST_MACHINE} ..."
  cp -af ${DEFAULT_PACKAGE_PATH}/* /rrshare/
  # set permissions
  chown -R abc:abc \
      /rrshare \
      /mnt
fi

# check upgrade
if [ -f ${UPGRADE_PACKAGE_PATH}/rrshareweb ]; then
  checksum_src=$(md5sum /rrshare/rrshareweb | cut -d " " -f 1)
  checksum_dst=$(md5sum ${UPGRADE_PACKAGE_PATH}/rrshareweb | cut -d " " -f 1)
  if [ ! $checksum_src = $checksum_dst ]; then
    echo "Upgrading ${HOST_MACHINE} ..."
    cp -af ${UPGRADE_PACKAGE_PATH}/* /rrshare/
    # set permissions
    chown -R abc:abc \
        /rrshare \
        /mnt
  fi
fi

